-- What did and did not land, after running seed.sql.
--
-- Paste the whole file into the Supabase SQL editor. It writes nothing. It
-- returns three result sets, and you want the first one to be empty.
--
-- Generated from supabase/seed.sql, which holds 136 places.

-- 1. Every place the seed should have written that the database does not have.
--    Empty means the seed landed in full.
with expected (slug) as (values
  ('luo-chun-ge'),
  ('da-hu-chun'),
  ('hen-jiu-yi-qian'),
  ('wei-xiang-zhai'),
  ('no-3-warehouse'),
  ('nanxiang-steamed-bun'),
  ('lao-zheng-xing'),
  ('shanghai-grandma'),
  ('international-hotel-bakery'),
  ('13de-marzo-caf'),
  ('rac-bar'),
  ('cuivre'),
  ('nono-s'),
  ('ren-he-guan'),
  ('huxi-laolongtang-noodles'),
  ('1515-steakhouse'),
  ('flair-rooftop-bar'),
  ('maison-lameloise'),
  ('no-3-warehouse-lujiazui'),
  ('dashu-restaurant'),
  ('kao-jiang'),
  ('yu-waitan'),
  ('fu-1039'),
  ('brut-eatery'),
  ('taian-table'),
  ('hanyu-noodle-shop'),
  ('jin-xiang-long'),
  ('wenzhou-beef-house'),
  ('ru-yuan'),
  ('jie-xiang-lou'),
  ('qingchun-pumen'),
  ('lou-wai-lou'),
  ('green-tea-restaurant'),
  ('gui-man-long'),
  ('zhiweiguan'),
  ('lao-tou-er-you-bao-xia'),
  ('yan-san-qu'),
  ('fuyuanju'),
  ('hang-ge-you-bao-xia'),
  ('ju-ying-noodles'),
  ('xinfeng-snacks'),
  ('wushan-roast-poultry'),
  ('shengli-river-food-street'),
  ('yan-san-qu-family-banquet'),
  ('rong-xian-noodle-house'),
  ('grandma-sun-s-congbaogui'),
  ('jue-mei-jia-seafood-wonton'),
  ('qian-ji-new-xiaoshan-cuisine'),
  ('pan-shui-da-yuan'),
  ('moxie-seafood-hotpot'),
  ('chao-jiu-shi-ba-dao'),
  ('kcooking-concept-korean'),
  ('wanxiang-city-viral-spots'),
  ('the-bund'),
  ('yu-garden-yuyuan-bazaar'),
  ('shanghai-tower-observation-deck'),
  ('nanjing-road'),
  ('former-french-concession'),
  ('shanghai-museum'),
  ('jing-an-temple'),
  ('jade-buddha-temple'),
  ('west-bund-art-district'),
  ('peace-hotel-fairmont'),
  ('huangpu-river-night-cruise'),
  ('era-acrobatics-show'),
  ('rooftop-bars-on-the-bund'),
  ('jazz-clubs-live-music'),
  ('shengjian-bao'),
  ('shanghai-fried-pork-cutlet'),
  ('french-concession-food-walk'),
  ('hairy-crab-oct-dec'),
  ('jia-jia-tang-bao'),
  ('din-tai-fung'),
  ('cube-story'),
  ('place'),
  ('umeplay'),
  ('place-2'),
  ('mc'),
  ('storm-island-immersive-center'),
  ('shanghai-international-circuit-kart-land'),
  ('peak-racing'),
  ('mosu-karting'),
  ('caolu-rooftop-karting'),
  ('lisu-racing-park'),
  ('wild-karting'),
  ('sleep-no-more'),
  ('partyday-super-star-carnival'),
  ('party-king-bowling-bar'),
  ('fantasy-city-archery-range'),
  ('new-world-golden-age'),
  ('qinchao-awakening-vr'),
  ('taixu-dreamscape'),
  ('orden-bowling-centre'),
  ('joypolis-vr-zones'),
  ('xixi-national-wetland-park'),
  ('grand-canal'),
  ('dongpo-pork'),
  ('longjing-tea-shrimp'),
  ('beggar-s-chicken'),
  ('west-lake-vinegar-fish'),
  ('hangzhou-style-noodles'),
  ('classic-restaurants'),
  ('qiandao-lake'),
  ('wuzhen-xitang'),
  ('liangzhu-archaeological-sites'),
  ('storm-island-next-gen-escape-rooms'),
  ('hallucination-immersive-theatre'),
  ('songcheng-romance-show'),
  ('impression-west-lake'),
  ('chuiyun-underground-river'),
  ('hongboyuan-outdoor-camp'),
  ('grand-canal-water-bus'),
  ('xiaohe-straight-street'),
  ('qiaoxi-historic-block'),
  ('nine-creeks-and-eighteen-gullies'),
  ('yunqi-bamboo-path'),
  ('liangzhu-ancient-city-ruins-park'),
  ('deshou-palace-museum'),
  ('liuhe-pagoda'),
  ('taiziwan-park'),
  ('manjuelong-osmanthus-valley'),
  ('wukang-mansion'),
  ('tianzifang'),
  ('pudong-to-bund-ferry'),
  ('foot-and-shoulder-massage'),
  ('shanghai-disneyland'),
  ('west-lake-and-bai-causeway'),
  ('west-lake-rowing-boat'),
  ('leifeng-pagoda'),
  ('lingyin-temple-and-feilai-peak'),
  ('longjing-village-tea-terraces'),
  ('meijiawu-tea-village'),
  ('hubin-in77-malls'),
  ('hefang-street'),
  ('yagu-resort'),
  ('ktv-after-party')
)
select e.slug as missing_slug
from expected e
left join public.places p on p.slug = e.slug
where p.slug is null
order by 1;

-- 2. What the database holds, by city and category, to compare with the seed:
--    shanghai 74, hangzhou 62. food 65, sight 25, activity 44, shopping 2.
select city, category, count(*) as rows
from public.places
group by city, category
order by city, category;

-- 3. Anything in the database the seed does not know about. Rows with
--    source 'user' were added in the app and are meant to be here. Anything
--    else is a leftover from an older extraction.
with expected (slug) as (values
  ('luo-chun-ge'),
  ('da-hu-chun'),
  ('hen-jiu-yi-qian'),
  ('wei-xiang-zhai'),
  ('no-3-warehouse'),
  ('nanxiang-steamed-bun'),
  ('lao-zheng-xing'),
  ('shanghai-grandma'),
  ('international-hotel-bakery'),
  ('13de-marzo-caf'),
  ('rac-bar'),
  ('cuivre'),
  ('nono-s'),
  ('ren-he-guan'),
  ('huxi-laolongtang-noodles'),
  ('1515-steakhouse'),
  ('flair-rooftop-bar'),
  ('maison-lameloise'),
  ('no-3-warehouse-lujiazui'),
  ('dashu-restaurant'),
  ('kao-jiang'),
  ('yu-waitan'),
  ('fu-1039'),
  ('brut-eatery'),
  ('taian-table'),
  ('hanyu-noodle-shop'),
  ('jin-xiang-long'),
  ('wenzhou-beef-house'),
  ('ru-yuan'),
  ('jie-xiang-lou'),
  ('qingchun-pumen'),
  ('lou-wai-lou'),
  ('green-tea-restaurant'),
  ('gui-man-long'),
  ('zhiweiguan'),
  ('lao-tou-er-you-bao-xia'),
  ('yan-san-qu'),
  ('fuyuanju'),
  ('hang-ge-you-bao-xia'),
  ('ju-ying-noodles'),
  ('xinfeng-snacks'),
  ('wushan-roast-poultry'),
  ('shengli-river-food-street'),
  ('yan-san-qu-family-banquet'),
  ('rong-xian-noodle-house'),
  ('grandma-sun-s-congbaogui'),
  ('jue-mei-jia-seafood-wonton'),
  ('qian-ji-new-xiaoshan-cuisine'),
  ('pan-shui-da-yuan'),
  ('moxie-seafood-hotpot'),
  ('chao-jiu-shi-ba-dao'),
  ('kcooking-concept-korean'),
  ('wanxiang-city-viral-spots'),
  ('the-bund'),
  ('yu-garden-yuyuan-bazaar'),
  ('shanghai-tower-observation-deck'),
  ('nanjing-road'),
  ('former-french-concession'),
  ('shanghai-museum'),
  ('jing-an-temple'),
  ('jade-buddha-temple'),
  ('west-bund-art-district'),
  ('peace-hotel-fairmont'),
  ('huangpu-river-night-cruise'),
  ('era-acrobatics-show'),
  ('rooftop-bars-on-the-bund'),
  ('jazz-clubs-live-music'),
  ('shengjian-bao'),
  ('shanghai-fried-pork-cutlet'),
  ('french-concession-food-walk'),
  ('hairy-crab-oct-dec'),
  ('jia-jia-tang-bao'),
  ('din-tai-fung'),
  ('cube-story'),
  ('place'),
  ('umeplay'),
  ('place-2'),
  ('mc'),
  ('storm-island-immersive-center'),
  ('shanghai-international-circuit-kart-land'),
  ('peak-racing'),
  ('mosu-karting'),
  ('caolu-rooftop-karting'),
  ('lisu-racing-park'),
  ('wild-karting'),
  ('sleep-no-more'),
  ('partyday-super-star-carnival'),
  ('party-king-bowling-bar'),
  ('fantasy-city-archery-range'),
  ('new-world-golden-age'),
  ('qinchao-awakening-vr'),
  ('taixu-dreamscape'),
  ('orden-bowling-centre'),
  ('joypolis-vr-zones'),
  ('xixi-national-wetland-park'),
  ('grand-canal'),
  ('dongpo-pork'),
  ('longjing-tea-shrimp'),
  ('beggar-s-chicken'),
  ('west-lake-vinegar-fish'),
  ('hangzhou-style-noodles'),
  ('classic-restaurants'),
  ('qiandao-lake'),
  ('wuzhen-xitang'),
  ('liangzhu-archaeological-sites'),
  ('storm-island-next-gen-escape-rooms'),
  ('hallucination-immersive-theatre'),
  ('songcheng-romance-show'),
  ('impression-west-lake'),
  ('chuiyun-underground-river'),
  ('hongboyuan-outdoor-camp'),
  ('grand-canal-water-bus'),
  ('xiaohe-straight-street'),
  ('qiaoxi-historic-block'),
  ('nine-creeks-and-eighteen-gullies'),
  ('yunqi-bamboo-path'),
  ('liangzhu-ancient-city-ruins-park'),
  ('deshou-palace-museum'),
  ('liuhe-pagoda'),
  ('taiziwan-park'),
  ('manjuelong-osmanthus-valley'),
  ('wukang-mansion'),
  ('tianzifang'),
  ('pudong-to-bund-ferry'),
  ('foot-and-shoulder-massage'),
  ('shanghai-disneyland'),
  ('west-lake-and-bai-causeway'),
  ('west-lake-rowing-boat'),
  ('leifeng-pagoda'),
  ('lingyin-temple-and-feilai-peak'),
  ('longjing-village-tea-terraces'),
  ('meijiawu-tea-village'),
  ('hubin-in77-malls'),
  ('hefang-street'),
  ('yagu-resort'),
  ('ktv-after-party')
)
select p.slug, p.name_en, p.city, p.category, p.source
from public.places p
left join expected e on e.slug = p.slug
where e.slug is null
order by p.source, p.slug;
