-- Catalog schema: the browsable library of places.
-- Run this in the Supabase SQL editor, or with `supabase db push`.
--
-- The itinerary itself is NOT here. It still lives in the browser, per the
-- original brief. Adding it later means one more migration, not a rewrite.

-- ---------------------------------------------------------------- districts

create table if not exists public.districts (
  id           text primary key,
  city         text not null check (city in ('shanghai', 'hangzhou')),
  name_zh      text not null,
  name_en      text not null,
  accent_color text not null
);

comment on table public.districts is
  'Districts as they appear in the source guides, plus one "Elsewhere" bucket per city.';

-- ------------------------------------------------------------------- places

create table if not exists public.places (
  -- Surrogate key on purpose. The human readable id is the slug, and slugs
  -- are derived from names: if a name is corrected the slug moves, and any
  -- itinerary pointing at it would break. The uuid never moves.
  id               uuid primary key default gen_random_uuid(),
  slug             text not null unique,

  name_zh          text not null,
  name_en          text not null,
  city             text not null check (city in ('shanghai', 'hangzhou')),
  district_id      text not null references public.districts (id) on update cascade,
  category         text not null check (category in ('food', 'sight', 'activity', 'shopping')),
  description      text not null default '',
  tags             text[] not null default '{}',

  price_min        integer check (price_min is null or price_min >= 0),
  price_max        integer check (price_max is null or price_max >= 0),
  address_zh       text,
  metro            text,
  duration_minutes integer check (duration_minutes is null or duration_minutes > 0),

  -- Which source file this came out of, or 'user' for one added in the app.
  source           text not null default 'user',
  created_by       uuid references auth.users (id) on delete set null,
  created_at       timestamptz not null default now(),

  constraint places_price_order
    check (price_min is null or price_max is null or price_min <= price_max)
);

create index if not exists places_city_category_idx on public.places (city, category);
create index if not exists places_district_idx      on public.places (district_id);

comment on column public.places.slug is
  'Stable human readable key, unique. Generated by scripts/extract.mjs.';

-- ---------------------------------------------------------------------- RLS

-- Supabase grants these two roles table privileges on the public schema by
-- default. Stating it here makes the migration self contained: RLS below is
-- then the only thing deciding who may do what.
grant usage on schema public to anon, authenticated;
grant select on public.districts, public.places to anon, authenticated;
grant insert, update, delete on public.places to authenticated;

alter table public.districts enable row level security;
alter table public.places    enable row level security;

-- The catalog is public: anyone opening the site can browse it.
drop policy if exists "districts are readable by everyone" on public.districts;
create policy "districts are readable by everyone"
  on public.districts for select
  using (true);

drop policy if exists "places are readable by everyone" on public.places;
create policy "places are readable by everyone"
  on public.places for select
  using (true);

-- Writing is closed to anonymous visitors. The anon key ships inside the
-- bundle and is readable by anyone who opens the page, so an insert policy
-- open to `anon` is an open write endpoint on the public internet, not a
-- private one. These policies grant writes to signed in users only, each
-- owning what they add.
drop policy if exists "signed in users can add places" on public.places;
create policy "signed in users can add places"
  on public.places for insert
  to authenticated
  with check (created_by = auth.uid());

drop policy if exists "authors can edit their own places" on public.places;
create policy "authors can edit their own places"
  on public.places for update
  to authenticated
  using (created_by = auth.uid())
  with check (created_by = auth.uid());

drop policy if exists "authors can remove their own places" on public.places;
create policy "authors can remove their own places"
  on public.places for delete
  to authenticated
  using (created_by = auth.uid());

-- If you would rather let anyone add a place without signing in, replace the
-- three policies above with the one below. Understand what it buys: anybody
-- who views the page can read the anon key out of the bundle and insert rows
-- into this table from a script, and you have no way to tell who did.
-- Reasonable for a throwaway personal deployment, not for a public site.
--
--   create policy "anyone can add a place"
--     on public.places for insert
--     to anon, authenticated
--     with check (source = 'user' and created_by is null);
