// Generated by scripts/extract.mjs from the files in source/.
// Do not edit by hand: run `npm run extract` instead.

import type { District } from '../types';

export const districts: District[] = [
  { id: "huangpu", city: "shanghai", nameZh: "黄浦区", nameEn: "Huangpu", accentColor: "#ea580c" },
  { id: "xuhui", city: "shanghai", nameZh: "徐汇区", nameEn: "Xuhui / French Concession", accentColor: "#16a34a" },
  { id: "jingan", city: "shanghai", nameZh: "静安区", nameEn: "Jing'an", accentColor: "#d97706" },
  { id: "pudong", city: "shanghai", nameZh: "浦东新区", nameEn: "Pudong", accentColor: "#0d9488" },
  { id: "yangpu", city: "shanghai", nameZh: "杨浦区", nameEn: "Yangpu", accentColor: "#7c3aed" },
  { id: "changning", city: "shanghai", nameZh: "长宁区", nameEn: "Changning", accentColor: "#2563eb" },
  { id: "putuo", city: "shanghai", nameZh: "普陀区", nameEn: "Putuo", accentColor: "#059669" },
  { id: "xihu", city: "hangzhou", nameZh: "西湖区", nameEn: "Xihu / West Lake", accentColor: "#0d9488" },
  { id: "shangcheng", city: "hangzhou", nameZh: "上城区", nameEn: "Shangcheng / Hubin", accentColor: "#c4693d" },
  { id: "gongshu", city: "hangzhou", nameZh: "拱墅区", nameEn: "Gongshu / Canal", accentColor: "#d97706" },
  { id: "xiaoshan", city: "hangzhou", nameZh: "萧山区", nameEn: "Xiaoshan", accentColor: "#dc2626" },
  { id: "binjiang", city: "hangzhou", nameZh: "滨江区", nameEn: "Binjiang / Qiantang", accentColor: "#7c3aed" },
  { id: "shanghai-other", city: "shanghai", nameZh: "其他", nameEn: "Elsewhere", accentColor: "#5f6b62" },
];
