// Generated by scripts/extract.mjs from the files in source/.
// Do not edit by hand: run `npm run extract` instead.

import type { Itinerary } from '../types';

export const starterItinerary: Itinerary = {
  name: "Hangzhou/Shanghai",
  days: [
    {
      id: "d0",
      date: "2026-09-17",
      label: "Departure night",
      items: [
      { id: "d0-01", customTitle: "Leave for the airport", startTime: "20:30", durationMinutes: 195, note: "Three hours before departure. Eat a proper dinner first, the flight meal lands at an odd hour." },
      { id: "d0-02", customTitle: "Flight to Shanghai Pudong", startTime: "23:45", note: "About 5.5 hours. Sleep on board, day one starts at 05:15 with no room until noon." },
      ],
    },
    {
      id: "d1",
      date: "2026-09-18",
      label: "Arrive, West Lake",
      items: [
      { id: "d1-01", customTitle: "Land at Pudong", startTime: "05:15", durationMinutes: 75, note: "Immigration and bags take 45 to 60 minutes at that hour." },
      { id: "d1-02", customTitle: "Airport breakfast", startTime: "06:30", durationMinutes: 140, note: "Congee, wonton noodles or a fast food set in arrivals. Nothing heavy before the coach. ¥30 to 60.", estCostMin: 30, estCostMax: 60 },
      { id: "d1-03", customTitle: "Airport coach to Hangzhou", startTime: "08:50", durationMinutes: 220, note: "Direct coach from Pudong, 3.5 to 4 hours. Backup: Metro Line 2 to Hongqiao then high speed rail, about one hour. Coach ¥100 to 130.", estCostMin: 100, estCostMax: 130 },
      { id: "d1-04", customTitle: "Hotel check in", startTime: "12:30", durationMinutes: 30, note: "Email the hotel to ask for an early check in. If the room is not ready, leave bags and eat first." },
      { id: "d1-05", customTitle: "Lunch near the hotel", startTime: "13:00", durationMinutes: 60, note: "A bowl of 片儿川 noodles or a small Hangzhou set. ¥40 to 80.", estCostMin: 40, estCostMax: 80 },
      { id: "d1-06", customTitle: "Nap, alarm set", startTime: "14:00", durationMinutes: 120, note: "Two hours maximum or the evening is gone." },
      { id: "d1-07", placeId: "west-lake-and-bai-causeway", startTime: "16:00", durationMinutes: 60, note: "Walk the Bai Causeway toward Broken Bridge and down the lakeside promenade. Sunset in late September falls around 18:05, so be in position by 17:30.", estCostMin: 0, estCostMax: 0 },
      { id: "d1-08", placeId: "west-lake-rowing-boat", startTime: "17:00", durationMinutes: 45, note: "A hand rowed boat out onto the lake. Best in the hour before sunset, and worth the small premium over the ferry boats.", estCostMin: 55, estCostMax: 70 },
      { id: "d1-09", customTitle: "Dinner at Hubin", startTime: "18:45", note: "Five minutes from the promenade. 东坡肉, 龙井虾仁, or 西湖醋鱼 if you are feeling brave. ¥60 to 130.", estCostMin: 60, estCostMax: 130 },
      ],
    },
    {
      id: "d2",
      date: "2026-09-19",
      label: "Wedding day",
      items: [
      { id: "d2-01", customTitle: "Wake and breakfast", startTime: "09:00", durationMinutes: 90, note: "Hotel breakfast or a 豆浆油条 shop nearby. Eat well, the banquet is hours away." },
      { id: "d2-02", customTitle: "Check out and transfer to the resort", startTime: "10:30", durationMinutes: 90, note: "Ride hailing is easiest with luggage. Have the address in Chinese ready for the driver." },
      { id: "d2-03", customTitle: "Settle in, rest, get ready", startTime: "12:00", durationMinutes: 120, note: "Light lunch at the resort if offered. Leave a full hour for hair, makeup and outfit." },
      { id: "d2-04", customTitle: "Head down to the venue", startTime: "14:00", durationMinutes: 88, note: "Early is the safe play. Help out, take photos, find your table without rushing." },
      { id: "d2-05", customTitle: "Couple walks in", startTime: "15:28", durationMinutes: 2, note: "Auspicious timing, so it starts on time. Phones charged." },
      { id: "d2-06", customTitle: "Ceremony and banquet until 20:00", startTime: "15:30", note: "Many rounds of toasts. Pace yourself, there is a second act." },
      { id: "d2-07", placeId: "ktv-after-party", startTime: "20:00", note: "Rooms are charged by the hour and usually split across the group. Drinks and snacks are extra.", estCostMin: 100, estCostMax: 250 },
      ],
    },
    {
      id: "d3",
      date: "2026-09-20",
      label: "Longjing tea hills",
      items: [
      { id: "d3-01", customTitle: "Check out, move back to the Hangzhou hotel", startTime: "09:30", durationMinutes: 90, note: "Check in again, or leave bags at the desk if the room is not ready." },
      { id: "d3-02", placeId: "longjing-village-tea-terraces", startTime: "11:00", durationMinutes: 120, note: "Walk the terraces and sit at a farmhouse tea house with a pot outdoors. September is not harvest season, so it is quiet and green.", estCostMin: 50, estCostMax: 150 },
      { id: "d3-03", placeId: "meijiawu-tea-village", startTime: "13:00", note: "The larger tea valley, thick with farmhouse restaurants. Order family style with the group, it is cheaper and you taste more.", estCostMin: 70, estCostMax: 130 },
      { id: "d3-04", customTitle: "Group dinner", startTime: "17:30", durationMinutes: 120, note: "Worth joining. Bigger table means more dishes and less deciding. ¥80 to 180.", estCostMin: 80, estCostMax: 180 },
      { id: "d3-05", placeId: "hubin-in77-malls", startTime: "19:30", note: "The lakeside mall cluster, open late, with a musical fountain on the lake side in the evening. Good for last minute anything and dessert.", estCostMin: 0, estCostMax: 0 },
      ],
    },
    {
      id: "d4",
      date: "2026-09-21",
      label: "Lingyin, then Shanghai",
      items: [
      { id: "d4-01", customTitle: "Breakfast and pack", startTime: "08:00", durationMinutes: 60, note: "Check out and leave luggage at the desk so you are not dragging it to the temple." },
      { id: "d4-02", placeId: "lingyin-temple-and-feilai-peak", startTime: "09:00", durationMinutes: 120, note: "Two tickets: one for the Feilai Peak scenic area and a second for the temple, bought inside. Calmest before 10:00 and worth two hours with the carved grottoes.", estCostMin: 75, estCostMax: 75 },
      { id: "d4-03", customTitle: "Lunch, then collect bags", startTime: "12:00", durationMinutes: 120, note: "The vegetarian noodles at the temple canteen are cheap and good. ¥25 to 70.", estCostMin: 25, estCostMax: 70 },
      { id: "d4-04", customTitle: "High speed rail to Shanghai", startTime: "14:00", durationMinutes: 150, note: "About one hour, departures every 15 to 30 minutes. Book a few days ahead for a Monday. Then Metro Line 2 to Lujiazui. Rail ¥73 to 95.", estCostMin: 73, estCostMax: 95 },
      { id: "d4-05", customTitle: "Check in, drop bags, head out", startTime: "16:30", durationMinutes: 60, note: "Riverside Pudong, so the skyline cluster and the Bund ferry are both close." },
      { id: "d4-06", placeId: "shanghai-tower-observation-deck", startTime: "17:30", durationMinutes: 120, note: "China’s tallest building at 632m. The deck on floors 118 to 119 gives a 360 degree view of the city. Book a timed slot near sunset.", estCostMin: 180, estCostMax: 180 },
      { id: "d4-07", customTitle: "Shanghainese dinner", startTime: "19:00", durationMinutes: 90, note: "红烧肉 braised pork belly, 生煎 pan fried buns, 小笼包 soup dumplings. ¥70 to 150.", estCostMin: 70, estCostMax: 150 },
      { id: "d4-08", placeId: "pudong-to-bund-ferry", startTime: "20:30", durationMinutes: 15, note: "The commuter ferry across the river for a couple of yuan. The cheapest skyline cruise in the city, and it runs late.", estCostMin: 2, estCostMax: 2 },
      { id: "d4-09", placeId: "the-bund", startTime: "20:45", note: "A 1.5km waterfront promenade lined with 52 historic colonial buildings facing the Pudong skyline across the river.", estCostMin: 0, estCostMax: 0 },
      ],
    },
    {
      id: "d5",
      date: "2026-09-22",
      label: "Shanghai wander",
      items: [
      { id: "d5-01", customTitle: "Sleep in, slow start", startTime: "09:30", durationMinutes: 150, note: "Your only unstructured day. Do not over plan it, Disney tomorrow is brutal on the legs." },
      { id: "d5-02", customTitle: "Lunch at a Michelin listed room", startTime: "12:00", durationMinutes: 120, note: "Lunch sets are far cheaper than dinner for the same kitchen. Book one to two weeks ahead for starred rooms. Bib Gourmand ¥60 to 150, one star lunch ¥300 to 700.", estCostMin: 60, estCostMax: 150 },
      { id: "d5-03", placeId: "former-french-concession", startTime: "14:00", durationMinutes: 90, note: "Plane tree streets, quiet lanes, coffee shops and low rise villas. The best half day of walking in Shanghai and it costs nothing.", estCostMin: 0, estCostMax: 0 },
      { id: "d5-04", placeId: "wukang-mansion", startTime: "15:30", durationMinutes: 60, note: "The flatiron shaped 1924 building at the fork of Wukang Road. The photo everyone takes, then coffee on Anfu Road.", estCostMin: 0, estCostMax: 0 },
      { id: "d5-05", placeId: "yu-garden-yuyuan-bazaar", startTime: "16:30", durationMinutes: 120, note: "A 400 year old Ming dynasty garden built in 1559, with rockeries, koi ponds and pavilions. The bazaar around it sells snacks and crafts.", estCostMin: 40, estCostMax: 40 },
      { id: "d5-06", placeId: "hen-jiu-yi-qian", startTime: "18:30", durationMinutes: 120, note: "\"Long Ago\": massively popular lamb skewer chain. Hulunbuir grassland lamb, open until 3 AM. Multiple branches across Shanghai, consistently draws weekend queues.", estCostMin: 100, estCostMax: 160 },
      { id: "d5-07", placeId: "foot-and-shoulder-massage", startTime: "20:30", durationMinutes: 90, note: "A 60 to 90 minute foot and shoulder massage. The correct choice the night before a theme park. Chains near Lujiazui are clean and reliable.", estCostMin: 150, estCostMax: 320 },
      ],
    },
    {
      id: "d6",
      date: "2026-09-23",
      label: "Disneyland",
      items: [
      { id: "d6-01", customTitle: "Early wake, breakfast, go", startTime: "06:45", durationMinutes: 75, note: "Metro Line 11 runs direct. Allow an hour from Lujiazui door to gate. Being there before opening is worth two extra rides." },
      { id: "d6-02", placeId: "shanghai-disneyland", startTime: "08:00", note: "A full day out. Metro Line 11 runs to the gate, allow an hour from Lujiazui. Buy the dated ticket in advance and be at the gate before opening.", estCostMin: 475, estCostMax: 700 },
      { id: "d6-03", customTitle: "Lunch in the park", startTime: "12:30", note: "Chase down the beef noodle soup, confirm which restaurant with the couple. Park meals ¥60 to 120. Bring sealed water.", estCostMin: 60, estCostMax: 120 },
      { id: "d6-04", customTitle: "Castle show and fireworks", startTime: "20:00", durationMinutes: 120, note: "Grab a spot 30 minutes early. Expect the exit crush and a packed metro." },
      { id: "d6-05", customTitle: "Back to the hotel", startTime: "22:00", note: "Start packing tonight. Tomorrow morning is tight." },
      ],
    },
    {
      id: "d7",
      date: "2026-09-24",
      label: "Fly home",
      items: [
      { id: "d7-01", customTitle: "Check out, leave bags with the hotel", startTime: "09:30", durationMinutes: 30, note: "Confirm the luggage room closing time and photograph the tag." },
      { id: "d7-02", customTitle: "Last walk and snack shopping", startTime: "10:00", durationMinutes: 120, note: "Longjing tea, 大白兔 sweets, 龙须酥 dragon beard candy, vacuum packed 酱鸭. Nothing you cannot check in. ¥100 to 400.", estCostMin: 100, estCostMax: 400 },
      { id: "d7-03", customTitle: "Quick lunch nearby", startTime: "12:00", durationMinutes: 90, note: "Close to the hotel, nothing that needs a queue." },
      { id: "d7-04", customTitle: "Collect bags and leave for Pudong", startTime: "13:30", durationMinutes: 60, note: "Hard deadline. Metro Line 2 is about 50 minutes with a change at Guanglan Rd, taxi 40 to 60 minutes. Taxi is safer with luggage. ¥160 to 220.", estCostMin: 160, estCostMax: 220 },
      { id: "d7-05", customTitle: "Check in at Pudong", startTime: "14:30", note: "Leave Lujiazui by 13:30. Tax refund counter first if you are claiming, it sits before security." },
      ],
    },
  ],
};
