// Generated by scripts/extract.mjs from the files in source/.
// Do not edit by hand: run `npm run extract` instead.

import type { Itinerary } from '../types';

export const starterItinerary: Itinerary = {
  name: "杭州/上海",
  days: [
    {
      id: "d0",
      date: "2026-09-17",
      label: "出发夜",
      items: [
      { id: "d0-01", customTitle: "Leave for the airport", startTime: "20:30", durationMinutes: 195, note: "Aim to be at check in three hours before a 23:45 departure. Eat a proper dinner before you go, the flight meal will land at an odd hour." },
      { id: "d0-02", customTitle: "Flight departs for 上海浦东 Shanghai Pudong", startTime: "23:45", note: "Roughly 5.5 hours. Sleep on board if you can, day one starts at 05:15 with no hotel room until noon." },
      ],
    },
    {
      id: "d1",
      date: "2026-09-18",
      label: "抵达 · 西湖日落",
      items: [
      { id: "d1-01", customTitle: "Land at 浦东国际机场 Pudong", startTime: "05:15", durationMinutes: 75, note: "Immigration and bags will take 45 to 60 minutes at that hour." },
      { id: "d1-02", customTitle: "Airport breakfast", startTime: "06:30", durationMinutes: 140, note: "Congee, wonton noodles or a fast food set in the arrivals area. Nothing heavy, you have a long bus ride next.", estCostMin: 30, estCostMax: 60 },
      { id: "d1-03", customTitle: "Airport coach to 杭州 Hangzhou", startTime: "08:50", durationMinutes: 220, note: "Direct long distance coach from Pudong, roughly 3.5 to 4 hours depending on traffic. Buy tickets at the counter in the arrivals hall or on the operator app. Backup option if the coach is full: Maglev or Metro Line 2 to Hongqiao, then high speed rail to Hangzhou East, about one hour of train time. Costs: Coach ¥100 to 130 · Rail backup ¥75 to 95", estCostMin: 100, estCostMax: 130 },
      { id: "d1-04", customTitle: "Hotel check in", startTime: "12:30", durationMinutes: 30, note: "Email the hotel now to ask for an early check in, you will arrive tired and the standard time is noon. If the room is not ready, leave bags and eat first." },
      { id: "d1-05", customTitle: "Lunch near the hotel", startTime: "13:00", durationMinutes: 60, note: "Keep it local and quick. A bowl of 片儿川 noodles or a small Hangzhou set is the right size before a nap.", estCostMin: 40, estCostMax: 80 },
      { id: "d1-06", customTitle: "Nap", startTime: "14:00", durationMinutes: 120, note: "Set an alarm. Two hours maximum or the evening is gone." },
      { id: "d1-07", placeId: "west-lake", startTime: "16:00", durationMinutes: 165, note: "Sunset falls around 18:03 to 18:07. Walk the 白堤 Bai Causeway toward 断桥 Broken Bridge, then down the lakeside promenade. Optional additions: a hand rowed boat, or 雷峰塔 Leifeng Pagoda for the sunset view over the water. Get to your sunset spot by 17:30, the good stretches fill up. Costs: Lake walk free · Boat ¥55 to 70 · Pagoda ¥40", estCostMin: 0, estCostMax: 0 },
      { id: "d1-08", customTitle: "Dinner near 湖滨 Hubin", startTime: "18:45", durationMinutes: 105, note: "The lakeside mall strip has plenty of options and is a five minute walk from the promenade. Try 东坡肉 braised pork, 龙井虾仁 shrimp with Longjing tea, or 西湖醋鱼 if you are feeling brave, it is divisive.", estCostMin: 60, estCostMax: 130 },
      { id: "d1-09", customTitle: "Back to the hotel, early night", startTime: "20:30", note: "Tomorrow is the wedding. Bank the sleep." },
      ],
    },
    {
      id: "d2",
      date: "2026-09-19",
      label: "婚礼日",
      items: [
      { id: "d2-01", customTitle: "Wake and breakfast", startTime: "09:00", durationMinutes: 90, note: "Hotel breakfast, or a local 豆浆油条 shop nearby. Eat well, the banquet does not start until the afternoon.", estCostMin: 15, estCostMax: 50 },
      { id: "d2-02", customTitle: "Check out and transfer to 雅谷度假村 Yagu Resort", startTime: "10:30", durationMinutes: 90, note: "Ride hailing is easiest with luggage. Confirm the resort address in Chinese on your phone the night before so you can show the driver.", estCostMin: 80, estCostMax: 200 },
      { id: "d2-03", customTitle: "Settle in, rest, get ready", startTime: "12:00", durationMinutes: 120, note: "Light lunch at the resort if it is offered. Leave a full hour for hair, makeup and outfit." },
      { id: "d2-04", customTitle: "Head down to the venue", startTime: "14:00", durationMinutes: 88, note: "Being early is the safe play. You can help, take photos, and find your table without rushing." },
      { id: "d2-05", customTitle: "Couple walks in", startTime: "15:28", note: "Auspicious timing, so it will start on time. Phones charged and ready." },
      { id: "d2-06", customTitle: "Ceremony and banquet", startTime: "15:30", durationMinutes: 270, note: "Expect many rounds of toasts. Pace yourself if you are drinking, there is a second act after this." },
      { id: "d2-07", customTitle: "After party at KTV", startTime: "20:00", note: "Rooms are usually charged by the hour and often split across the group, drinks and snacks are extra.", estCostMin: 100, estCostMax: 250 },
      ],
    },
    {
      id: "d3",
      date: "2026-09-20",
      label: "龙井茶山",
      items: [
      { id: "d3-01", customTitle: "Check out of the resort", startTime: "09:30", durationMinutes: 90, note: "Move luggage back to the Zhejiang Hotel and check in again, or leave bags at the front desk if the room is not ready.", estCostMin: 80, estCostMax: 200 },
      { id: "d3-02", placeId: "tea-plantation-day", startTime: "11:00", durationMinutes: 120, note: "Most likely 龙井村 Longjing Village or 梅家坞 Meijiawu. Walk the terraces, sit at a farmhouse tea house, and drink a pot outdoors. September is not harvest season, so it is quiet and green rather than busy. If anyone wants to buy tea, buy from a farmhouse rather than a roadside stall, and expect to be offered several grades. Costs: Tea house ¥50 to 150 · Tea to bring home ¥200 up", estCostMin: 50, estCostMax: 150 },
      { id: "d3-03", customTitle: "Lunch at a 农家乐 farmhouse restaurant", startTime: "13:00", durationMinutes: 270, note: "These are all over the tea villages. Order family style with the group, it works out cheaper and you taste more.", estCostMin: 70, estCostMax: 130 },
      { id: "d3-04", customTitle: "Group dinner", startTime: "17:30", durationMinutes: 120, note: "Worth joining. Bigger table means more dishes and a better spread, and it is easier than finding somewhere on your own.", estCostMin: 80, estCostMax: 180 },
      { id: "d3-05", placeId: "in77", startTime: "19:30", note: "Lakeside mall cluster, open late, with a musical fountain on the lake side in the evening. Good for last minute anything and a decent dessert stop." },
      ],
    },
    {
      id: "d4",
      date: "2026-09-21",
      label: "灵隐寺 · 转场上海",
      items: [
      { id: "d4-01", customTitle: "Breakfast and pack", startTime: "08:00", durationMinutes: 60, note: "Check out and leave luggage at the desk so you are not dragging it to the temple." },
      { id: "d4-02", placeId: "lingyin-temple", startTime: "09:00", durationMinutes: 180, note: "Two tickets: one for 飞来峰 Feilai Peak scenic area and a second for the temple itself, bought inside. Go early, it is calmest before 10:00. Allow two hours including the carved grottoes along the walk in. Skip it without guilt if everyone is tired, you have a train to catch.", estCostMin: 45, estCostMax: 45 },
      { id: "d4-03", customTitle: "Lunch, then collect bags", startTime: "12:00", durationMinutes: 120, note: "The vegetarian noodles at the temple canteen are cheap and surprisingly good if you are still up there.", estCostMin: 25, estCostMax: 70 },
      { id: "d4-04", customTitle: "High speed rail 杭州东 to 上海虹桥", startTime: "14:00", durationMinutes: 150, note: "Around one hour, departures every 15 to 30 minutes. Book seats a few days ahead for a Monday afternoon. Then Metro Line 2 across to Lujiazui, roughly 45 minutes, or a taxi for about 40 minutes. Costs: Rail ¥73 to 95 · Metro ¥7 · Taxi ¥120 to 160", estCostMin: 73, estCostMax: 95 },
      { id: "d4-05", customTitle: "Check in, drop bags, head out", startTime: "16:30", durationMinutes: 60, note: "You are on the Pudong riverside, which puts the skyline cluster and the ferry to the Bund within easy reach." },
      { id: "d4-06", placeId: "lujiazui-skyline", startTime: "17:30", durationMinutes: 90, note: "Either go up 上海中心 Shanghai Tower for the highest view, or stay at ground level and walk the riverside. Book tower tickets online for a timed slot near sunset. Costs: Tower ¥180 · Riverside walk free", estCostMin: 180, estCostMax: 180 },
      { id: "d4-07", customTitle: "Dinner", startTime: "19:00", durationMinutes: 90, note: "Local 本帮菜 Shanghainese if you want the classics: 红烧肉 braised pork belly, 生煎 pan fried buns, 小笼包 soup dumplings.", estCostMin: 70, estCostMax: 150 },
      { id: "d4-08", placeId: "the-bund", startTime: "20:30", note: "Take the 轮渡 ferry across from Pudong for a couple of yuan, it is the cheapest skyline cruise in the city. The Bund facade lights usually stay on until around 22:00 to 23:00, so do not leave it too late. Costs: Ferry ¥2 · Waterfront free", estCostMin: 2, estCostMax: 2 },
      ],
    },
    {
      id: "d5",
      date: "2026-09-22",
      label: "上海漫游",
      items: [
      { id: "d5-01", customTitle: "Sleep in, slow start", startTime: "09:30", durationMinutes: 150, note: "Your only unstructured day. Do not over plan it, Disney tomorrow is brutal on the legs." },
      { id: "d5-02", customTitle: "Lunch: a Michelin listed room", startTime: "12:00", durationMinutes: 120, note: "Lunch sets at starred and Bib Gourmand places in Shanghai are far cheaper than dinner for nearly the same kitchen. Book one or two weeks ahead for the starred ones. Bib Gourmand noodle and dumpling shops need no booking at all and are the better value. Costs: Bib Gourmand ¥60 to 150 · One star lunch ¥300 to 700", estCostMin: 60, estCostMax: 150 },
      { id: "d5-03", placeId: "wukang-road-and-the-former-french-concession", startTime: "14:00", durationMinutes: 150, note: "Plane tree lined streets, low rise villas, coffee shops and small boutiques. The best walking in Shanghai and it costs nothing. Wukang Mansion at the fork is the photo everyone takes. Costs: Free · coffee ¥30 to 55", estCostMin: 0, estCostMax: 0 },
      { id: "d5-04", customTitle: "Activity four: pick one", startTime: "16:30", durationMinutes: 120, note: "豫园 Yu Garden and the old town bazaar for classical gardens and snack stalls, garden entry around ¥40. Or 田子坊 Tianzifang for lane alleys and craft shops, free. Or 南京东路 Nanjing East Road if the group wants straightforward shopping.", estCostMin: 0, estCostMax: 40 },
      { id: "d5-05", customTitle: "Dinner: 串串香 skewer hotpot", startTime: "18:30", durationMinutes: 120, note: "The skewer hotpot idea from your draft fits here nicely. You pick sticks from a fridge, cook them at the table, and pay by the stick, so the bill is whatever you make it. Lively and good for a group.", estCostMin: 80, estCostMax: 160 },
      { id: "d5-06", customTitle: "Activity five: massage, or the Bund if you missed it", startTime: "20:30", note: "A 60 to 90 minute foot and shoulder massage is the correct choice the night before a theme park. Chains near Lujiazui are clean and reliable.", estCostMin: 150, estCostMax: 320 },
      ],
    },
    {
      id: "d6",
      date: "2026-09-23",
      label: "上海迪士尼",
      items: [
      { id: "d6-01", customTitle: "Early wake, breakfast, go", startTime: "06:45", durationMinutes: 75, note: "Metro Line 11 runs direct to Disney Resort station. From Lujiazui allow about an hour door to gate. Being at the gate before opening is worth two extra rides.", estCostMin: 6, estCostMax: 9 },
      { id: "d6-02", placeId: "disneyland", startTime: "08:00", note: "Tickets are dated and priced by demand tier, so a late September midweek day usually sits in a mid tier. Buy in advance through the official channel, gate prices and availability are worse. Add the paid queue skip only if the app shows long waits, it is priced per ride. Costs: Ticket ¥475 to 700 · Queue skip ¥80 up per ride", estCostMin: 475, estCostMax: 700 },
      { id: "d6-03", customTitle: "Food inside the park", note: "The beef noodle soup you mentioned is worth chasing down, confirm which restaurant with the couple before you go. Park food runs ¥60 to ¥120 a meal. Bring your own sealed water, it saves a fortune.", estCostMin: 120, estCostMax: 250 },
      { id: "d6-04", customTitle: "Evening castle show and fireworks", startTime: "20:00", durationMinutes: 120, note: "Grab a viewing spot about 30 minutes early. Expect the exit crush afterwards, and expect the metro to be packed." },
      { id: "d6-05", customTitle: "Back to the hotel", startTime: "22:00", note: "Start packing tonight. Tomorrow morning is tight." },
      ],
    },
    {
      id: "d7",
      date: "2026-09-24",
      label: "回家",
      items: [
      { id: "d7-01", customTitle: "Check out, leave bags with the hotel", startTime: "09:30", durationMinutes: 30, note: "Confirm the luggage room closing time and take a tag photo." },
      { id: "d7-02", customTitle: "Last walk and snack shopping", startTime: "10:00", durationMinutes: 120, note: "Worth buying: Longjing tea, 大白兔 White Rabbit sweets, 龙须酥 dragon beard candy, vacuum packed 酱鸭 soy duck. Do not buy anything you cannot check in.", estCostMin: 100, estCostMax: 400 },
      { id: "d7-03", customTitle: "Quick lunch nearby", startTime: "12:00", durationMinutes: 90, note: "Keep it close to the hotel. Nothing that needs a queue.", estCostMin: 40, estCostMax: 90 },
      { id: "d7-04", customTitle: "Collect bags and leave for Pudong", startTime: "13:30", durationMinutes: 60, note: "This is the hard deadline in your draft. Metro Line 2 takes about 50 minutes from Lujiazui with one change at Guanglan Road, a taxi is 40 to 60 minutes but traffic dependent. Taxi is the safer call with luggage and a fixed flight. Costs: Metro ¥8 · Taxi ¥160 to 220", estCostMin: 8, estCostMax: 8 },
      { id: "d7-05", customTitle: "Check in at the airport", startTime: "14:30", note: "Tax refund counter first if you shopped enough to claim, it sits before security and the queue can be long." },
      { id: "d7-06", customTitle: "Fly home" },
      ],
    },
  ],
};
